# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"


# --- Rofi ---


# Wallpaper configuration.
[wallpaper]
custom_paths = []  # List of paths to search for wallpapers.

# Global rofi configuration.
[rofi]
scale = 10  # Rofi default scaling.
# 'hyprlock.sh select' configuration.
[rofi.hyprlock]
scale = 10  # Scaling for hyprlock.

# 'animation.sh select' configuration.
[rofi.animation]
scale = 10  # Scaling for animation.

# swwwallselect.sh configuration.
[rofi.wallpaper]
scale = 10  # Scaling for wallpaper.

# themeselect.sh configuration.
[rofi.theme]
scale = 6  # Scaling for theme selector.


# wlogout configuration.
[wlogout]
style = 1  # Style for wlogout.


# wallbash configuration.
[wallbash]
skip_template = [""]  # Templates to skip when using wallbash.

# waybar configuration.
[waybar]
font = "JetBrainsMono Nerd Font"  # Font for waybar.
scale = 10  # Total scaling for waybar.
icon_size = 10  # Icon size for waybar.
position = "top"  # A fallback position of the waybar.  

# volumecontrol.sh configuration.
[volume]
notify = true  # Enable notifications for volume control.
steps = 5  # Number of steps to increase/decrease volume.
boost = false  # Enable volume boost.
boost_limit = 120  # Volume boost limit.

# Hyprland configuration.
[hyprland]
browser = "firefox"  # Browser.
editor = "nvim"  # Editor.
explorer = "dolphin"  # File manager.
idle = "hypridle"  # Idle manager.
lockscreen = "lockscreen.sh"  # Lockscreen.
terminal = "kitty"  # Terminal.
quickapps = "kitty"  # Quick apps.
bar = "waybar"  # Bar.
color_scheme = "prefer-dark"  # Color scheme.
gtk_theme = "Wallbash-Gtk"  # GTK theme.
icon_theme = "YAMIS"  # Icon theme.
cursor_size = 24  # Cursor size.
cursor_theme = "Qogir"  # Cursor theme.
button_layout = ""  # Button layout. (gtk only)
document_font_size = 10  # Document font size.
font = "JetBrainsMono Nerd Font"  # Font.
font_antialiasing = "rgba"  # Font antialiasing.
font_hinting = "full"  # Font hinting.
font_size = 10  # Font size.
monospace_font = "CaskaydiaCove Nerd Font Mono"  # Monospace font.
monospace_font_size = 10  # Monospace font size.
background_path = ""  # LockScreen's Background path.

# Hyprland start configuration.
[hyprland_start]
apptray_bluetooth = "blueman-applet"  # Bluetooth applet.
auth_dialogue = "polkitkdeauth.sh"  # Authentication dialogue.
bar = "hyde-shell waybar --watch"  # Bar.
battery_notify = "batterynotify.sh"  # Battery notification script.
dbus_share_picker = "dbus-update-activation-environment --systemd --all"  # DBus share picker.
idle_daemon = "hypridle"  # Idle daemon.
image_clipboard = "wl-paste --type image --watch cliphist store"  # Image clipboard.
network_manager = "nm-applet --indicator"  # Network manager.
notifications = "swaync"  # Notifications.
removable_media = "udiskie --no-automount --smart-tray"  # Removable media manager.
systemd_share_picker = "systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"  # Systemd share picker.
text_clipboard = "wl-paste --type text --watch cliphist store"  # Text clipboard.
wallpaper = "$scrPath/wallpaper.sh --global"  # Wallpaper script.
xdg_portal_reset = "resetxdgportal.sh"  # XDG portal reset script.

# mediaplayer.py configuration.
[mediaplayer]
prefix_playing = ""  # Prefix for playing media.
prefix_paused = "  "  # Prefix for paused media.
max_length = 50  # Max length of song and artist string.
standby_text = "  Music"  # To display on standby.
artist_track_separator = "  "  # Separator symbols to display between artist and track.

